AllCops:
  DisplayCopNames: true
  ExtraDetails: true
  TargetRubyVersion: 2.2

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FileName:
  Exclude:
  - 'lib/stamp-l10n.rb'

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Max: 20
